[project]
name = "time-vault-nft"
version = "1.0.0"
description = "Lock STX and mint proof NFT"
authors = []
telemetry = false
cache_dir = ".cache"
requirements = []

[contracts.time-vault-nft]
path = "contracts/time-vault-nft.clar"
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
